# Generated by Django 5.1.3 on 2024-12-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_email_verified_customuser_ev_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
